### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth' (BLENDER 4.0)

### ISSUE THREAD

**Issue by MetricCepheid** [vidsicious612/hmx-importer#2]
![image](https://github.com/user-attachments/assets/ef74fa98-acb0-46d2-8c4e-d1a2bd06d49a)

Blender 4.0 has changed the way autosmoothing works. Just giving a heads up.
<https://blenderartists.org/t/blender-4-1-auto-smooth-is-now-a-modifier-only/1488922>

**Comment by vidsicious612** [comment]
yeah, only works on 3.6 because of that
